name: CI

on:
  push:
    branches: [main]

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform/envs/dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
        run: terraform validate

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
